stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: python:3.12
  before_script:
    - pip install black
  script:
    - black --check app/ tests/

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - set ENV=test
    - pytest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ml-app .
